# Собираем в го
FROM golang:1.25.3

ENV BIN_FILE /opt/previewer/previewer-app
ENV CODE_DIR /go/src/

WORKDIR ${CODE_DIR}

# Кэшируем слои с модулями
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . ${CODE_DIR}

# Собираем статический бинарник Go (без зависимостей на Си API),
# иначе он не будет работать в alpine образе.
ARG LDFLAGS
RUN CGO_ENABLED=0 go build \
        -ldflags "$LDFLAGS" \
        -o ${BIN_FILE} cmd/server/*

# На выходе тонкий образ
FROM alpine:3.9

LABEL SERVICE="previewer"
LABEL MAINTAINERS="adettelle"

ENV BIN_FILE "/opt/previewer/previewer-app"
COPY --from=build ${BIN_FILE} ${BIN_FILE}

# ENV CONFIG_FILE ./configs/calendar_cfg.json 
# COPY ./configs/calendar_cfg.json ${CONFIG_FILE}

CMD ${BIN_FILE} 